version: "3"

services:
  api:
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost"
      EMAIL_URL: "smtp://mail:1025"
      CORS_ORIGIN_WHITELIST: "http://localhost:4200,http://localhost:8080"
      CSRF_TRUSTED_ORIGINS: "http://localhost"
      REGISTER_VERIFICATION_URL: "http://localhost:4200/verify-user/"
      RESET_PASSWORD_VERIFICATION_URL: "http://localhost:4200/set-password/?token={token}"
      REGISTER_EMAIL_VERIFICATION_URL: "http://localhost:4200/verify-email/"
    ports:
      - "8000:8000"
    volumes:
      - ./data/fixtures/:/fixtures/
      - ./code/snypy-backend/:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000

  mail:
    image: msztolcman/sendria:v2.2.2.0
    ports:
      - "1080:1080"

  static:
    profiles:
      - donotstart

  ui:
    environment:
      REST_API_URL: "http://localhost:8000"
    ports:
      - "8080:80"
