# https://hub.docker.com/_/python
FROM python:3.12-slim
WORKDIR /usr/src/app/snypy
COPY /code/snypy-backend/requirements/base.txt /usr/src/app/snypy/requirements.txt
RUN pip install --no-cache-dir pip gunicorn psycopg2-binary -U
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
