name: build_images

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["api", "static", "ui"]

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if build and push is required
        run: if docker-compose pull ${{ matrix.service }}; then echo "SKIP=1" >> $GITHUB_ENV; else echo "SKIP=0" >> $GITHUB_ENV; fi 

      - name: Build container image
        run: docker-compose build ${{ matrix.service }}
        if: env.SKIP != 1

      - name: Push container image
        run: docker-compose push ${{ matrix.service }}
        if: env.SKIP != 1
